### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by FastEddy760** [twilio-labs/plugin-signal2020#5]
### Issue Summary
Unable to launch Signal 2020 CLI

### Steps to Reproduce
1. run command `twilio signal2020`
2. Error returned
3. Removed app (un-installed), reinstalled, repeated and used latest.

### Technical details:
Run `twilio signal2020 --diagnostics -o=json` and paste it in here:
```
# paste diagnostics content here
$ twilio signal2020 -d -o=json
    Error: Package exports for 
    '/Users/eddy/.twilio-cli/node_modules/clipboardy' do not define a '.' 
    subpath
    Code: MODULE_NOT_FOUND


### [optional] output from your log file.

Log file is empty

**Comment by childish-sambino** [comment]
@FastEddy760 What version of node are you running?

**Comment by FastEddy760** [comment]
$ node -v
v13.1.0

**Comment by ktalebian** [comment]
@FastEddy760 when trying to install using node v13.1.0, I get

> The engine "node" is incompatible with this module. Expected version "^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7". Got "13.1.0"

Try bumping to the latest version of v13 (v13.14.0) and see if that helps.

**Comment by FastEddy760** [comment]
Did a Brew uninstall, then downloaded latest stable version.  That worked. All good. 


$ brew uninstall --ignore-dependencies node

https://nodejs.org/en/

$ node -v
v14.13.0
