### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by Albatrossd** [twilio-labs/plugin-signal2020#6]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, or screencasts.

### Steps to Reproduce
1. twilio plugins:remove @twilio-labs/plugin-signal2020
2. twilio plugins:install @twilio-labs/plugin-signal2020@latest
3. twilio signal2020
    SyntaxError: Unexpected token 'export'
4. twilio signal2020 -d -o=json
SyntaxError: Unexpected token 'export'
### Technical details:
Run `twilio signal2020 --diagnostics -o=json` and paste it in here:
SyntaxError: Unexpected token 'export'# paste diagnostics content here

node -v
v13.6.0
zsh
macOS Catalina
```

### [optional] screenshots:
Please only add this if it does not contain any personal information you are uncomfortable sharing in public.

### [optional] output from your log file.
The log file is located in your temporary directory. In macOS and Linux that's at `$TMPDIR/twilio-signal-dev-mode.log`. In Windows it's going to be at `%Temp%\twilio-signal-dev-mode.log`. You can also find the path as part of the diagnostics output. If you are unsure about this, skip adding it.

**Important** Make sure to not include any personal information or tokens as this is all public!

**Comment by ktalebian** [comment]
@Albatrossd when trying to install using node `13.6.0` I'm getting a ton of errors such as 

> browserslist@4.14.5: The engine "node" is incompatible with this module. Expected version "^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7". Got "13.6.0"

Try bumping to the latest version of v13 (v13.14.0) and see if that helps.

**Comment by Albatrossd** [comment]
I ran latest and v14.13.0 fixed the issue, thank you.
